CREATE TABLE sleuth_users (
    id  int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name text NOT NULL,
    last_name text NOT NULL,
    user_name varchar NOT NULL UNIQUE,
    password varchar(72) NOT NULL
);